const fs = require('fs');
const path = require('path');

// Setup browser globals for the scripts
global.window = global;
global.TextEncoder = require('util').TextEncoder;
global.TextDecoder = require('util').TextDecoder;

// Load dependencies
const odinCode = fs.readFileSync(path.join(__dirname, 'odin_browser.js'), 'utf8');
const parserCode = fs.readFileSync(path.join(__dirname, 'parser.js'), 'utf8');
const csaveIoCode = fs.readFileSync(path.join(__dirname, 'csave_io.js'), 'utf8');

const { Script } = require('vm');
const script = new Script(odinCode + '\n' + parserCode + '\n' + csaveIoCode);
const context = { window: global, TextEncoder: global.TextEncoder, TextDecoder: global.TextDecoder, console: console, ArrayBuffer: ArrayBuffer, Uint8Array: Uint8Array, DataView: DataView };
script.runInNewContext(context);

const CsaveIO = context.window.CsaveIO;



// Buscamos un archivo csave de prueba
const testFile = path.join(__dirname, 'save (3).csave');
if (!fs.existsSync(testFile)) {
    console.error("Test file not found!");
    process.exit(1);
}

const originalBuffer = fs.readFileSync(testFile);
const originalBytes = new Uint8Array(originalBuffer.buffer, originalBuffer.byteOffset, originalBuffer.byteLength);

console.log("=== RUNNING W1 TESTS ===");

// 1. Load csave real -> write sin apply -> bytes identicos o hash identico
let parser = CsaveIO.loadCsave(originalBytes.buffer.slice(originalBytes.byteOffset, originalBytes.byteOffset + originalBytes.byteLength));
let writtenBytes = CsaveIO.writeCsave(parser);
if (originalBytes.length !== writtenBytes.length) {
    console.warn(`[WARN] Original length: ${originalBytes.length}, Written length: ${writtenBytes.length}. (Puede variar ligeramente por regeneración de strings si Odin no era canon)`);
} else {
    let diff = false;
    for(let i=0; i<originalBytes.length; i++) {
        if (originalBytes[i] !== writtenBytes[i]) {
            diff = true; break;
        }
    }
    console.log("[TEST 1] Write without apply matches bytes:", !diff ? "PASSED" : "FAILED (Bytes differ)");
}

// Extraemos json inicial
let initialJson = CsaveIO.toPortJson(parser);
console.log(`[TEST 4] toPortJson mapas["0"] exists:`, initialJson.mapas && initialJson.mapas["0"] ? "PASSED" : "FAILED");

// 2. apply: carrots = 200 -> write -> load -> 200
let modJson = JSON.parse(JSON.stringify(initialJson, (k, v) => typeof v === 'bigint' ? Number(v) : v));
modJson.carrots = 200;

// 3. apply: mover un furniture de sloc 0 (x,y)
if (modJson.mapas["0"].placements.length > 0) {
    modJson.mapas["0"].placements[0].x = 99;
    modJson.mapas["0"].placements[0].y = 88;
}

// Test new inventory item using generator
modJson.inventory.push({
    id: 12345,
    qty: 1,
    invType: 1
    // verificationID should be auto-generated by applyPortJson
});

CsaveIO.applyPortJson(parser, modJson);
let modBytes = CsaveIO.writeCsave(parser);

// Load de vuelta
let parser2 = CsaveIO.loadCsave(modBytes.buffer.slice(modBytes.byteOffset, modBytes.byteOffset + modBytes.byteLength));
let finalJson = CsaveIO.toPortJson(parser2);

console.log(`[TEST 2] Carrots roundtrip (Expected 200, Got ${finalJson.carrots}):`, finalJson.carrots === 200 ? "PASSED" : "FAILED");

let moved = false;
if (finalJson.mapas["0"].placements.length > 0) {
    const p0 = finalJson.mapas["0"].placements[0];
    if (p0.x === 99 && p0.y === 88) moved = true;
}
console.log(`[TEST 3] Furniture move roundtrip:`, moved ? "PASSED" : "FAILED");

const addedItem = finalJson.inventory.find(i => i.id === 12345);
console.log(`[TEST 5] New Item Verification ID generated:`, (addedItem && addedItem.verificationID && addedItem.verificationID !== 0) ? "PASSED" : "FAILED", addedItem ? `(Got ${addedItem.verificationID})` : "");

console.log("=== TESTS COMPLETE ===");
